### ISSUE TITLE
Bug: Uncrafting Enchanted Items

### ISSUE THREAD

**Issue by BiatuAutMiahn** [crazysnailboy/UncraftingTable#13]
When attempting to uncraft enchanted items to enchanted books, I see no output. I even tried repairing the items and still no enchanted book comes out.

**Comment by crazysnailboy** [comment]
Please could you let me know which version of the mod you're using for which version of Minecraft, what item you're attempting to uncraft and what enchantments it has? Thanks :)

**Comment by BiatuAutMiahn** [comment]
Sorry, you can close this. The item has to have enough durability to uncraft, and the book is automatically exported when taking uncrafted materials.

**Comment by BiatuAutMiahn** [comment]
on side note, is there anyway to say...use less XP for an item with little durability.

**Comment by BiatuAutMiahn** [comment]
And is there a way to allow getting the enchantment from an an item with little or no durability?

**Comment by crazysnailboy** [comment]
Good to hear :)

There are two ways of doing uncrafting for damaged items. One will give you all the materials back in exchange for more XP, and the other gives you a partial return for the default amount of XP. You can change the method in the config.

If you use the "Xell75 & Zenen" method, you can get the enchants and the full materials back regardless of durability. You can also set the minimum and maximum levels to determine how much XP it will cost.
