### ISSUE TITLE
Feature: Allow uncrafting Enchanted books?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [crazysnailboy/UncraftingTable#14]
How about the ability to uncraft an enchanted book, returning XP to player (the amount required to get that same enchanted book from an enchantment table minus the cost of the uncrafting)

**Comment by crazysnailboy** [comment]
Hi, I'm sorry I should probably have replied to this a long time ago, but this isn't a feature I'm going to add I'm afraid.
