### ISSUE TITLE
[1.12] Crash on load (Fixed)

### ISSUE THREAD

**Issue by Morphyloon** [crazysnailboy/UncraftingTable#20]
UncraftingTable: 1.8-beta1
forge: 1.12-14.21.0.2324
minecraft: 1.12

[crash-2017-06-14_19.10.58-client.txt](https://github.com/crazysnailboy/UncraftingTable/files/1076154/crash-2017-06-14_19.10.58-client.txt)

**Comment by crazysnailboy** [comment]
Yes I'm aware of this one unfortunately.

I built the mod against Forge 1.12-14.21.0.232**2**, and then 1.12-14.21.0.232**4** was released a couple of hours later which changed the way recipe registration works.

Forge 1.12-14.21.0.2324 and 1.12-14.21.0.2325 have their own problems with corrupted level.dat files, so I'd advise you stay away from those for a while. Downgrade Forge if you can. I'll update this mod once those issues have been sorted.

Thanks for letting me know though :)

**Comment by crazysnailboy** [comment]
Version [1.8-beta2](https://github.com/crazysnailboy/UncraftingTable/releases/download/v1.12-1.8-beta2/1.12.UncraftingTable-1.8-beta2.jar) resolves this.
