### ISSUE TITLE
Uncrafting table 1.4.4 for 1.7.10 and AE2 crash (Fixed)

### ISSUE THREAD

**Issue by stevojhall** [crazysnailboy/UncraftingTable#21]
playing project ozone 2 with this added and i am getting this crash with certain items (block of quartz 155 and redstone caparator 404) i think it is because of the use of pure nether quartz crystal as a recipe, only thing that seems to be added and in both recipes thats from ae2.
[https://pastebin.com/MVDwTEpf](url)

**Comment by crazysnailboy** [comment]
OK I'll take a look at that, thanks for letting me know :)

**Comment by crazysnailboy** [comment]
I think I found the problem!

Could you try this one and let me know if it works please?

[UncraftingTable-1.7.10-1.4.4b.jar](https://drive.google.com/uc?export=download&id=0B1LBp40P2UyBeWRpcUE5aTU2QmM)

**Comment by stevojhall** [comment]
it works great so far, thanks. i really never thought you would update it for such an "old" version of minecraft lol, just thought i should let you know just in case. ill keep you up to date if anything changes. :)

**Comment by crazysnailboy** [comment]
Cool :) I'd not going to be adding any more features for 1.7.10 - I'm focusing on 1.10.2 and up for new stuff - but I'll fix continue to fix game breaking bugs on the older versions if any crop up. Thanks again for finding it and telling me about it!
