### ISSUE TITLE
[1.12] Tooltip not showing in UI and other oddities

### ISSUE THREAD

**Issue by Morphyloon** [crazysnailboy/UncraftingTable#22]
For awhile now (think it started just after Forge decided to completely rewrite mod registration) when I use the table, it works but the tooltip that tells me what an item is when mouse-hovered, won't show only in the Uncrafting table's UI.

[This is probably another bug/conflict with the newest Forge]
I can drop a stack of iron blocks, uncraft them as normal but, without leaving the uncrafting table's UI, the next attempt, it says it's not uncraftible-- on the first try. Remove the blocks and place them again in the slot and suddenly I can uncraft them into ingots. Every other uncrafting attempt results in a warning of "that's not uncraftible". Weird.

**Comment by crazysnailboy** [comment]
Thanks for highlighting this - I'll look into it

**Comment by crazysnailboy** [comment]
Hi, I've uploaded [v1.8-beta4](https://minecraft.curseforge.com/projects/jglrxavpoks-uncrafting-table/files/2450097/download) which should resolve these and a couple of other issues.

Please let me know whether that works for you :)
