### ISSUE TITLE
[Resource] es_MX / es_ES translation

### ISSUE THREAD

**Issue by Dorzar** [crazysnailboy/UncraftingTable#24]
//Translate by: Dorzar / VeryHardChamp
//Act.: 27/07/2017

tile.uncrafting_table.name=Mesa de destrucción

item.diamondNugget.name=Pepita de diamante
item.emeraldNugget.name=Pepita de esmeralda
item.leatherStrip.name=Tira de cuero

achievement.createDecraftTable=Como en los viejos tiempos
achievement.createDecraftTable.desc=¡Fabrica una mesa de destrucción!
achievement.uncraftAnything=¡Destruyelo!
achievement.uncraftAnything.desc=¡Por destruir tu primer objeto!
achievement.uncraftDiamondHoe=¡Destruye un azadón de diamante!
achievement.uncraftDiamondHoe.desc=Al menos tendrás algo devuelta.
achievement.uncraftJunk=¡Hora de reciclar!
achievement.uncraftJunk.desc=Este objeto no tiene usos.
achievement.uncraftDiamondShovel=Enfoque más barato
achievement.uncraftDiamondShovel.desc=Las palas de hierro son mejores.
achievement.porteManteauAchievement=¡Todo en uno!
achievement.porteManteauAchievement.desc=ยงk <3 Para todos los jugadores

container.uncrafting=Mesa de destrucción
container.uncrafting.cost=Costo de EXP: %1$s

uncrafting.result.ready=Listo
uncrafting.result.impossible=Imposible de destruir
uncrafting.result.needMoreStacks=Necesitas %1$s objetos(s)

stat.uncrafteditems=Objetos destruidos

**Comment by crazysnailboy** [comment]
Thank you for the translation :)

Please could you add the rest of the language strings so that I can include a complete file? I've created a PasteBin with those you've done already and the others (currently still in English) here:

https://pastebin.com/5Mdss6T1

Thanks!

**Comment by Dorzar** [comment]
The rest of the translation is for the configuration (not shown in the game) ... but, consider it done :)
I will comment again when I am finished.
