### ISSUE TITLE
[1.12] Not retrieving xp

### ISSUE THREAD

**Issue by EphisPaF** [crazysnailboy/UncraftingTable#28]
Hi, 

I'm using your mod on my server in MC 1.12
But at the moment there is no xp consumming when uncrafting item (or unchanting).
This is too overpowered for players.
I have changed the config file to stop using unchanting with enchantmentCost=1000, but it's not working, it didn't stop players to get echantements books and items.

Have you any idea on how to fix it or is it a version issue ?

**Comment by crazysnailboy** [comment]
Hi, thanks for highlighting this - it appears I disabled the xp cost for some reason (I honestly have no idea why - I must have been testing something, or maybe just being dim) and forgot to reenable it before publishing a release. I'll get a new version out to fix it.

As for changing the enchantment cost to 1000, I don't think that will work as the cost range is capped at 10. I'd need to test it but I think a value higher than 10 will be treated as 10.

**Comment by crazysnailboy** [comment]
Apologies for the delay in getting to this - I've now published [v1.8-beta6](https://minecraft.curseforge.com/projects/jglrxavpoks-uncrafting-table/files/2480822/download) which should resolve it.
