### ISSUE TITLE
[1.12.1] Nuggets Not Using Ore Dictionary

### ISSUE THREAD

**Issue by MokahTGS** [crazysnailboy/UncraftingTable#29]
It looks like diamond and emerald nuggets aren't using the ore dictionary when they are broken down.

**Comment by crazysnailboy** [comment]
They were registered in the ore dictionary, but the recipes I'd added when converting to JSON weren't ore dictionary aware. I've published [v1.8-beta6](https://minecraft.curseforge.com/projects/jglrxavpoks-uncrafting-table/files/2480822/download) which resolves this. Thanks for letting me know :)
