### ISSUE TITLE
Enhancements to the uncrafting GUI

### ISSUE THREAD

**Issue by crazysnailboy** [crazysnailboy/UncraftingTable#4]
- [ ] The uncrafting operation should not be completed until the user removes an item from the uncrafting grid. This renders the compute slot unnecessary for it's current function, and becomes just for adding books to capture enchantments.

- [ ] When an uncrafting operation cannot be completed due to insufficient XP, the result should still be displayed in the uncrafting grid, but faded out like the Twilight Forest mod.

- [ ] The "Ready" message and "Compute" text are unnecessary and should be removed.

- [ ] The XP cost should be displayed in green or red, depending on whether the user has sufficient XP, like th vanilla anvil GUI. The same display area should be used for the messages indicating that an item is not uncraftable, or that the input stack is doesn't contain enough items.

- [ ] The arrow between the input slots and output grid is too long, with the point being clipped currently. Replace this with the vanilla arrow used on other GUIs.

- [ ] The arrow should be rendered with a cross over it when the uncrafting operation cannot be completed, like the vanilla anvil GUI.

- [ ] The GUI title is displayed one pixel too high, and the player inventory title is one pixel too far left, compared to vanilla GUIs.

**Comment by Zelly9191** [comment]
I like these ideas good luck ill test the new builds as soon as there out.

**Comment by jglrxavpok** [comment]
I have been working on some enhancements this afternoon [on my fork](https://github.com/jglrxavpok/csbUncraftingTable), I'll do a pull request soon(tm)

Here's a video of what it looks like for the moment:

[The video](https://youtu.be/ydI_2YJ1ZlI)

**Comment by crazysnailboy** [comment]
Hey, looks cool! Not having the uncrafting happen right away is definitely an improvement I think. I checked out your fork, looks like you've been busy! Look forward to seeing the end result when it's finished :)

**Comment by jglrxavpok** [comment]
[And here it is with enchantments!](https://youtu.be/4EVdCCHsnXg)


Uncrafting damaged items do not work in my fork so I won't do the pull request before a few days

**Comment by crazysnailboy** [comment]
Closing as this is all now implemented
