### ISSUE TITLE
New Textures / Resource Pack support

### ISSUE THREAD

**Issue by crazysnailboy** [crazysnailboy/UncraftingTable#8]
I was thinking it would be nice to be able to provide some alternative textures for the mod for those people who use resource packs.

Faithful 32x32 is a very popular pack, so some textures based on the current ones but derived from Faithful's 32 pixel equivalents could work well for Faithful users. I checked Faithful's licensing terms and they do allow this.

There's also a resource pack called Unity which has extensive mod support and nice textures, so I was thinking that some textures in the Unity style would also be nice.

What do you reckon? Is this a good idea, and would you be willing to make them? If so, are there any other resource packs you think we should be considering?

**Comment by Zelly9191** [comment]
Sure i'll see what i can do however i'll be very busy this month with a number of things. Sorry if i don't get back immediately to posts it may take me a bit. :) i'm not sure how popular BDcraft may be doable. typically I don't work on/ create Minecraft textures above 16x16  but i'll give it a shot.   :) (I'm sure it won't be too difficult.)

**Comment by crazysnailboy** [comment]
A very kind Reddit user did some new textures including Faithful 32 style ones, so I'll close this as I don't need it any more :)
